export const TABS = 'DRAFT_tabs'
export const TEMP_TAB = 'DRAFT_temp_tab'
export const SELECTED_COMPONENT_HASH = 'DRAFT_Selected_Component_Hash'
export const DRAWER_VIEW = 'DRAFT_drawer_view'
export const DRAWER_IS_OPEN = 'DRAFT_drawer_is_open'
export const EDIT_DRAWER_IS_OPEN = 'DRAFT_edit_drawer_open'
export const EDIT_DRAWER_ITEM = 'DRAFT_edit_item'